<?php
$EmailFrom = "ContactForm@DavidGibbons.me";
$EmailTo = "dgibbns@gmail.com";
$Subject = "DavidGibbons.me Contact Form";
$Name = Trim(stripslashes($_POST['inputName'])); 
$Tel = Trim(stripslashes($_POST['inputPhone'])); 
$Email = Trim(stripslashes($_POST['inputEmail']));
$Message = Trim(stripslashes($_POST['inputMessage'])); 

// prepare email body text
$Body = "This message was generated by a user submitting a message on the Contact Form of DGibbons.org.";
$Body .= "\n";
$Body .= "Name: ";
$Body .= $Name;
$Body .= "\n";
$Body .= "Tel: ";
$Body .= $Tel;
$Body .= "\n";
$Body .= "Email: ";
$Body .= $Email;
$Body .= "\n";
$Body .= "Message: ";
$Body .= $Message;
$Body .= "\n";

// send email 
$success = mail($EmailTo, $Subject, $Body, "From: <$EmailFrom>");

// redirect to success page 
if ($success){
  print "<meta http-equiv=\"refresh\" content=\"0;URL=contact?success\">";
}
else{
  print "<meta http-equiv=\"refresh\" content=\"0;URL=contact?error\">";
}
?>
